/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pablogb.digestvuelos.gui;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import pablogb.digestvuelos.componentes.DatosCompanya;
import pablogb.digestvuelos.componentes.EditarCompanya;
import pablogb.digestvuelos.dto.Companya;
import pablogb.digestvuelos.gui.FrmCompanyas;
import pablogb.digestvuelos.logica.CompanyaTableModel;
import pablogb.digestvuelos.logica.LogicaNegocio;
import pablogb.digestvuelos.logica.CompanyaTableModel;
import pablogb.digestvuelos.logica.LogicaNegocio;
import pablogb.digestvuelos.readers.CompanyasCsvReader;

/**
 *
 * @author Pablo
 */
public class FrmCompanyas extends javax.swing.JFrame {

    /**
     * Creates new form FrmCompanyas
     */
    private static final FrmCompanyas INSTANCE = new FrmCompanyas();

    public static FrmCompanyas getInstance() {
        return INSTANCE;
    }

    public FrmCompanyas() {
        initComponents();
        loadCompanies();
    }

    public void updateTable() {
        loadCompanies();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompanyas = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        tblCompanyas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCompanyas);

        btnConsultar.setText("Consultar / Editar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnAlta.setText("Dar de alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnConsultar)
                .addGap(152, 152, 152)
                .addComponent(btnAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnAlta)
                    .addComponent(btnEliminar))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed

        JFrame frame = new JFrame("Añadir una Nueva Compañia");
        DatosCompanya datosCompanya = DatosCompanya.getInstance();

        datosCompanya.setFrmCompanyas(this);

        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(datosCompanya);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        int fila = tblCompanyas.getSelectedRow();
        if (fila >= 0) {
            Companya selecCompanya = ((CompanyaTableModel) tblCompanyas.getModel()).lstRegistros.get(fila);

            EditarCompanya editarPanel = EditarCompanya.getInstance();
            editarPanel.setCompanya(selecCompanya);

            editarPanel.setFrmCompanyas(this);

            JFrame frame = new JFrame("Editar Compañia");
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.getContentPane().add(editarPanel);
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        } else {

            JOptionPane.showMessageDialog(this, "Por favor seleccione una compañia para editar");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int selectedRow = tblCompanyas.getSelectedRow();
        if (selectedRow >= 0) {
            Companya companyaAEliminar = ((CompanyaTableModel) tblCompanyas.getModel()).lstRegistros.get(selectedRow);

            eliminarCompanyaDelCsv(companyaAEliminar);

            ((CompanyaTableModel) tblCompanyas.getModel()).lstRegistros.remove(selectedRow);
            ((CompanyaTableModel) tblCompanyas.getModel()).fireTableDataChanged();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor seleccione una compañia para eliminar.");
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCompanyas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCompanyas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCompanyas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCompanyas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCompanyas().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCompanyas;
    // End of variables declaration//GEN-END:variables

    private void loadCompanies() {

        List<Companya> listaActualizada = LogicaNegocio.getAllCompanyas();

        if (tblCompanyas.getModel() instanceof CompanyaTableModel) {

            CompanyaTableModel model = (CompanyaTableModel) tblCompanyas.getModel();
            model.lstRegistros = listaActualizada;
            model.fireTableDataChanged();
        } else {
            tblCompanyas.setModel(new CompanyaTableModel(listaActualizada));
        }
    }

    private void eliminarCompanyaDelCsv(Companya companyaAEliminar) {
        CompanyasCsvReader csvReader = new CompanyasCsvReader();
        List<Companya> Companyas = csvReader.readCompanyas();

        Companyas.removeIf(comp -> comp.getCodigo().equals(companyaAEliminar.getCodigo()));

        LogicaNegocio.escribirCompanyasCsv(Companyas);
        
        updateTable();
        

    }
}
