/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pablogb.digestvuelos.gui;

import pablogb.digestvuelos.gui.FrmCompanyas;
import pablogb.digestvuelos.gui.FrmMain;
import pablogb.digestvuelos.logica.LogicaNegocio;
 

/**
 *
 * @author Pablo
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        LogicaNegocio.initializeProgram();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	btnCompanyas = new javax.swing.JButton();
        btnPaneles = new javax.swing.JButton();
        btnVuelosBase = new javax.swing.JButton();
        btnVuelosDiarios = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        btnCompanyas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCompanyas.setText("Compañías aéreas");
        btnCompanyas.setActionCommand("btnCompanyasCommand");
        btnCompanyas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompanyasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompanyas);

        btnPaneles.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPaneles.setText("Paneles de información");
        btnPaneles.setActionCommand("btnPanelesCommand");
        btnPaneles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelesActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaneles);

        btnVuelosBase.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVuelosBase.setText("Vuelos base");
        btnVuelosBase.setActionCommand("btnVuelosBaseCommand");
        getContentPane().add(btnVuelosBase);

        btnVuelosDiarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVuelosDiarios.setText("Vuelos aéreos");
        btnVuelosDiarios.setActionCommand("btnVuelosDiariosCommand");
        btnVuelosDiarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVuelosDiariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVuelosDiarios);
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnPanelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPanelesActionPerformed

    private void btnVuelosDiariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVuelosDiariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVuelosDiariosActionPerformed

    private void btnCompanyasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompanyasActionPerformed
        FrmCompanyas.getInstance().setVisible(true);
    }//GEN-LAST:event_btnCompanyasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompanyas;
    private javax.swing.JButton btnPaneles;
    private javax.swing.JButton btnVuelosBase;
    private javax.swing.JButton btnVuelosDiarios;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
