/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pablogb.digestvuelos.gui;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import pablogb.digestvuelos.componentes.DatosCompanya;
import pablogb.digestvuelos.componentes.DatosVueloBase;
import pablogb.digestvuelos.componentes.EditarCompanya;
import pablogb.digestvuelos.componentes.EditarVueloBase;
import pablogb.digestvuelos.dto.Companya;
import pablogb.digestvuelos.dto.VueloBase;
import pablogb.digestvuelos.gui.FrmVuelosBase;
import pablogb.digestvuelos.logica.LogicaNegocio;
import pablogb.digestvuelos.logica.VueloBaseTableModel;
import pablogb.digestvuelos.logica.LogicaNegocio;
import pablogb.digestvuelos.readers.CompanyasCsvReader;
import pablogb.digestvuelos.readers.VuelosBaseCsvReader;

/**
 *
 * @author Pablo
 */
public class FrmVuelosBase extends javax.swing.JFrame {

    /**
     * Creates new form FrmCompanyas
     */
    private static final FrmVuelosBase INSTANCE = new FrmVuelosBase();

    public static FrmVuelosBase getInstance() {
        return INSTANCE;
    }
    
   

    public FrmVuelosBase() {
        initComponents();
        loadVuelosBase();
    }

    public void updateTable() {
        loadVuelosBase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsultar = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVuelosBase = new javax.swing.JTable();

        btnConsultar.setText("Consultar / Editar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnAlta.setText("Dar de alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblVuelosBase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblVuelosBase);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnConsultar)
                .addGap(152, 152, 152)
                .addComponent(btnAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnAlta)
                    .addComponent(btnEliminar))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed

        JFrame frame = new JFrame("Añadir un Nuevo Vuelo Base");
        DatosVueloBase datosVueloBase = DatosVueloBase.getInstance();


        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(datosVueloBase);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        int fila = tblVuelosBase.getSelectedRow();
        if (fila >= 0) {
            VueloBase selecVuelo = ((VueloBaseTableModel) tblVuelosBase.getModel()).lstRegistros.get(fila);

            EditarVueloBase editarPanel = EditarVueloBase.getInstance();
            editarPanel.setVueloBase(selecVuelo);

            editarPanel.setFrmVuelosBase(this);

            JFrame frame = new JFrame("Editar Vuelo Base");
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.getContentPane().add(editarPanel);
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        } else {

            JOptionPane.showMessageDialog(this, "Por favor seleccione un vuelo para editar");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblVuelosBase.getSelectedRow();
        if (fila >= 0) {
            VueloBase vueloAEliminar = ((VueloBaseTableModel) tblVuelosBase.getModel()).lstRegistros.get(fila);

            eliminarVueloBaseDelCsv(vueloAEliminar);

            ((VueloBaseTableModel) tblVuelosBase.getModel()).lstRegistros.remove(fila);
            ((VueloBaseTableModel) tblVuelosBase.getModel()).fireTableDataChanged();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un vuelo para eliminar.");
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVuelosBase.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVuelosBase.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVuelosBase.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVuelosBase.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVuelosBase().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblVuelosBase;
    // End of variables declaration//GEN-END:variables

    private void loadVuelosBase() {

        List<VueloBase> listaActualizada = LogicaNegocio.getAllVuelosBase();

        if (tblVuelosBase.getModel() instanceof VueloBaseTableModel) {

            VueloBaseTableModel model = (VueloBaseTableModel) tblVuelosBase.getModel();
            model.lstRegistros = listaActualizada;
            model.fireTableDataChanged();
        } else {
            tblVuelosBase.setModel(new VueloBaseTableModel(listaActualizada));
        }
    }

    private void eliminarVueloBaseDelCsv(VueloBase vueloBaseAEliminar) {
        VuelosBaseCsvReader csvReader = new VuelosBaseCsvReader();
        List<VueloBase> vuelos = csvReader.readVuelosBase();

        vuelos.removeIf(comp -> comp.getCodigoVuelo().equals(vueloBaseAEliminar.getCodigoVuelo()));

        LogicaNegocio.escribirVuelosBaseCsv(vuelos);
        
        updateTable();
        

    }
}
